In [1]:
import numpy as np
import pandas as pd

## **Categorical Encoding - 1 feature** ##

### **레이블인코딩 I/O , 변환 결과** ###

In [62]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X = ['Male', 'Female', 'Female']
#X = np.array(['Male', 'Female', 'Female']).reshape(-1,1)
le.fit(X)

LabelEncoder()

In [63]:
print(le.classes_)
print(le.transform(X))
print(le.inverse_transform([1,0]))

['Female' 'Male']
[1 0 0]
['Male' 'Female']


### **오디널인코딩 I/O , 변환 결과** ###

In [64]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
#X = [['Male'], ['Female'], ['Female']]
X = np.array(['Male', 'Female', 'Female']).reshape(-1,1)
enc.fit(X)

OrdinalEncoder(categories='auto', dtype=<class 'numpy.float64'>)

In [76]:
print(enc.categories_)
print(enc.transform(X)) # shape (3,1)
print(enc.inverse_transform([[1],[0]]))

[array(['Female', 'Male'], dtype='<U6')]
[[1.]
 [0.]
 [0.]]
[['Male']
 ['Female']]


### **원핫인코딩 I/O , 변환 결과** ###

In [68]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder()
#X = [['Male'], ['Female'], ['Female']]
X = np.array(['Male', 'Female', 'Female']).reshape(-1,1)
oh.fit(X)

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [99]:
print(oh.categories_)
print(oh.transform(X).toarray()) #shape (3.2) 
print(oh.inverse_transform([[0, 1], [1, 0]]))

[array(['Female', 'Male'], dtype='<U6')]
[[0. 1.]
 [1. 0.]
 [1. 0.]]
[['Male']
 ['Female']]


## **Categorical Encoding -  N feature** ##

### **레이블인코딩 I/O** ###

In [100]:
'''하나의 feature(주로 타켓 변수) 변환을 위한 것이므로 사용할 수 없음'''

'하나의 feature(주로 타켓 변수) 변환을 위한 것이므로 사용할 수 없음'

### **오디널인코딩 I/O, 변활결과** ###

In [101]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
X = [['Male', 1], ['Female', 3], ['Female', 2]]
#X = np.array(['Male', 'Female', 'Female']).reshape(-1,1)
enc.fit(X)

OrdinalEncoder(categories='auto', dtype=<class 'numpy.float64'>)

In [110]:
print(enc.categories_)
print(enc.transform(X)) # shape (3,2)
print(enc.inverse_transform([[1,0], [0,1], [1,1], [1,2], [0,1]]))

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
[[1. 0.]
 [0. 2.]
 [0. 1.]]
[['Male' 1]
 ['Female' 2]
 ['Male' 2]
 ['Male' 3]
 ['Female' 2]]


### **원핫인코딩 I/O , 변환 결과** ###

In [111]:
from sklearn.preprocessing import OneHotEncoder
oh = OneHotEncoder()
X = [['Male', 1], ['Female', 3], ['Female', 2]]
#X = np.array(['Male', 'Female', 'Female']).reshape(-1,1)
oh.fit(X)

OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [118]:
print(oh.categories_)
print(oh.transform(X).toarray()) #shape (3.5) 
print(oh.inverse_transform([[0, 1, 1, 0, 0], [1, 0, 0, 0, 1]]))

[array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
[[0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 1. 0.]]
[['Male' 1]
 ['Female' 3]]


In [116]:
oh.get_feature_names()

array(['x0_Female', 'x0_Male', 'x1_1', 'x1_2', 'x1_3'], dtype=object)

In [127]:
oh.transform([['Male', 1]]).toarray()

array([[0., 1., 1., 0., 0.]])

## **Categorical Encoding -  apply real data(df)** ##

In [2]:
bike=pd.read_csv('bike_train2.csv')
bike.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  target  
0        81        0.0       3          13      16  
1        80        0.0       8          32      40  
2        80        0.0       5          27      32  
3        75        0.0       3          10      13  
4        75        0.0       0           1       1

### **one feature** ###

In [3]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [5]:
#오디널인코딩 적용
enc = OrdinalEncoder()
enc.fit(bike['season'].values.reshape(-1,1))

OrdinalEncoder(categories='auto', dtype=<class 'numpy.float64'>)

In [6]:
enc.transform(bike['season'].values.reshape(-1,1))

array([[0.],
       [0.],
       [0.],
       ...,
       [3.],
       [3.],
       [3.]])

In [7]:
DATA = bike.copy()
DATA['season'] = enc.transform(bike['season'].values.reshape(-1,1))
DATA.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00     0.0        0           0        1  9.84  14.395   
1  2011-01-01 01:00     0.0        0           0        1  9.02  13.635   
2  2011-01-01 02:00     0.0        0           0        1  9.02  13.635   
3  2011-01-01 03:00     0.0        0           0        1  9.84  14.395   
4  2011-01-01 04:00     0.0        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  target  
0        81        0.0       3          13      16  
1        80        0.0       8          32      40  
2        80        0.0       5          27      32  
3        75        0.0       3          10      13  
4        75        0.0       0           1       1

In [25]:
#원핫인코딩 적용
oh = OneHotEncoder(categories='auto') #sparse=False
oh.fit(bike['season'].values.reshape(-1,1))

OneHotEncoder(categorical_features=None, categories='auto',
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [26]:
oh.transform(bike['season'].values.reshape(-1,1))

<10886x4 sparse matrix of type '<class 'numpy.float64'>'
	with 10886 stored elements in Compressed Sparse Row format>

In [27]:
DATA = bike.copy()
oh_result = oh.transform(bike['season'].values.reshape(-1,1))
OneHot = pd.DataFrame(oh_result, columns = ['field_name'+"_"+str(int(i)) for i in range(oh_result.shape[1])])
DATA = pd.concat([DATA, OneHot], axis=1, sort=False)
DATA = DATA.drop('season', axis=1)
DATA.head()

ValueError: Shape of passed values is (10886, 1), indices imply (10886, 4)

In [28]:
oh.categories_[0]

array([1, 2, 3, 4], dtype=int64)

In [32]:
oh.transform(np.array(oh.categories_).reshape(-1,1)).toarray()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
print(type(oh.transform(np.array(oh.categories_).reshape(-1,1))))
encoded_class = oh.transform(np.array(oh.categories_).reshape(-1,1))
encoded_class

<class 'scipy.sparse.csr.csr_matrix'>


<4x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [35]:
encoded_class = encoded_class.toarray() if not isinstance(encoded_class, np.ndarray) else encoded_class
print(type(encoded_class))
encoded_class

<class 'numpy.ndarray'>


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
if isinstance(oh.transform(np.array(oh.categories_).reshape(-1,1)), np.ndarray):
    print('np')
else:
    print(type(oh.transform(np.array(oh.categories_).reshape(-1,1))))

<class 'scipy.sparse.csr.csr_matrix'>


In [13]:
oh.transform(np.array(oh.categories_).reshape(4,1)).tolist()

[[1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0]]

In [18]:
oh.transform(oh.categories_[0].reshape(-1,1))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
oh.transform(np.array(oh.categories_[0]).reshape(-1,1)).tolist()

[[1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0]]

### **two feature** ##
변환은 가능하지만 한 피쳐씩 처리하는 것이 재사용할 때 일관성 있음

In [250]:
def int_to_str(x):
    if x == 1:
        return '1'
    else:
        return '0'

bike['workingday'] =list(map(int_to_str, bike['workingday']))

In [268]:
#오디널인코딩 적용 
enc = OrdinalEncoder()
enc.fit(bike[['season', 'holiday']].values.reshape(-1,2))

OrdinalEncoder(categories='auto', dtype=<class 'numpy.float64'>)

In [269]:
enc.transform(bike[['season', 'holiday']].values.reshape(-1,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [3., 0.],
       [3., 0.],
       [3., 0.]])

In [271]:
enc.categories_

[array([1, 2, 3, 4], dtype=int64), array([0, 1], dtype=int64)]

In [299]:
#원핫인코딩 적용 
oh = OneHotEncoder(categories='auto', sparse=False)
oh.fit(bike[['season', 'holiday']].astype('str').values.reshape(-1,2))

OneHotEncoder(categorical_features=None, categories='auto',
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=False)

In [300]:
oh.transform(bike[['season', 'holiday']].astype('str').values.reshape(-1,2))

array([[1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0.],
       ...,
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 1., 0.]])

In [301]:
oh.get_feature_names()

array(['x0_1', 'x0_2', 'x0_3', 'x0_4', 'x1_0', 'x1_1'], dtype=object)

In [308]:
oh.inverse_transform([[1., 0., 0., 0., 1. ,0.]])

array([['1', '0']], dtype=object)

## **save preprocessed data** ##

In [3]:
bike=pd.read_csv('bike_train2.csv')
bike.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  target  
0        81        0.0       3          13      16  
1        80        0.0       8          32      40  
2        80        0.0       5          27      32  
3        75        0.0       3          10      13  
4        75        0.0       0           1       1

In [4]:
from sklearn.preprocessing import MinMaxScaler
mm_scaler = MinMaxScaler()
mm_scaler.fit(bike['temp'].values.reshape(-1,1))
scaled_temp = mm_scaler.transform(bike['temp'].values.reshape(-1,1))
bike['temp'] = scaled_temp
bike.head()

datetime  season  holiday  workingday  weather      temp   atemp  \
0  2011-01-01 00:00       1        0           0        1  0.224490  14.395   
1  2011-01-01 01:00       1        0           0        1  0.204082  13.635   
2  2011-01-01 02:00       1        0           0        1  0.204082  13.635   
3  2011-01-01 03:00       1        0           0        1  0.224490  14.395   
4  2011-01-01 04:00       1        0           0        1  0.224490  14.395   

   humidity  windspeed  casual  registered  target  
0        81        0.0       3          13      16  
1        80        0.0       8          32      40  
2        80        0.0       5          27      32  
3        75        0.0       3          10      13  
4        75        0.0       0           1       1

In [5]:
param = dict(field_name="datetime,registered")
print(param, type(param))

{'field_name': 'datetime,registered'} <class 'dict'>


In [6]:
param['field_name']
f_name = param['field_name']
f_name.split(',')

['datetime', 'registered']

In [7]:
if len(f_name.split(',')) !=1:
    for name in f_name.split(','):
        print(name)
        
else:
    print('1')

datetime
registered


In [8]:
def drop_columns(data, columns):
    if len(columns.split(',')) != 1:
        for column_name in columns.split(','):
            data = data.drop(columns=[column_name], axis=1)        
    else:
        data = data.drop(columns=[columns], axis=1)
    return data

bike_2 = drop_columns(bike, f_name)
bike_2

season  holiday  workingday  weather      temp   atemp  humidity  \
0           1        0           0        1  0.224490  14.395        81   
1           1        0           0        1  0.204082  13.635        80   
2           1        0           0        1  0.204082  13.635        80   
3           1        0           0        1  0.224490  14.395        75   
4           1        0           0        1  0.224490  14.395        75   
5           1        0           0        2  0.224490  12.880        75   
6           1        0           0        1  0.204082  13.635        80   
7           1        0           0        1  0.183673  12.880        86   
8           1        0           0        1  0.224490  14.395        75   
9           1        0           0        1  0.306122  17.425        76   
10          1        0           0        1  0.367347  19.695        76   
11          1        0           0        1  0.346939  16.665        81   
12          1        0           0        1  0.408163  21.210        77   
13          1        0           0        2  0.448980  22.725        72   
14          1        0           0        2  0.448980  22.725        72   
15          1        0           0        2  0.428571  21.970        77   
16          1        0           0        2  0.408163  21.210        82   
17          1        0           0        2  0.428571  21.970        82   
18          1        0           0        3  0.408163  21.210        88   
19          1        0           0        3  0.408163  21.210        88   
20          1        0           0        2  0.387755  20.455        87   
21          1        0           0        2  0.387755  20.455        87   
22          1        0           0        2  0.387755  20.455        94   
23          1        0           0        2  0.448980  22.725        88   
24          1        0           0        2  0.448980  22.725        88   
25          1        0           0        2  0.428571  21.970        94   
26          1        0           0        2  0.408163  21.210       100   
27          1        0           0        2  0.448980  22.725        94   
28          1        0           0        2  0.448980  22.725        94   
29          1        0           0        3  0.408163  21.210        77   
...       ...      ...         ...      ...       ...     ...       ...   
10856       4        0           1        1  0.367347  19.695        46   
10857       4        0           1        1  0.367347  19.695        46   
10858       4        0           1        1  0.346939  16.665        50   
10859       4        0           1        1  0.346939  17.425        50   
10860       4        0           1        1  0.326531  16.665        49   
10861       4        0           1        1  0.326531  17.425        49   
10862       4        0           1        1  0.285714  15.910        61   
10863       4        0           1        1  0.285714  15.910        65   
10864       4        0           1        1  0.265306  15.150        65   
10865       4        0           1        1  0.244898  13.635        75   
10866       4        0           1        1  0.224490  12.120        75   
10867       4        0           1        1  0.244898  14.395        75   
10868       4        0           1        1  0.224490  12.880        75   
10869       4        0           1        1  0.244898  13.635        75   
10870       4        0           1        1  0.224490  12.880        87   
10871       4        0           1        1  0.265306  14.395        75   
10872       4        0           1        1  0.306122  16.665        70   
10873       4        0           1        1  0.387755  20.455        54   
10874       4        0           1        1  0.387755  20.455        54   
10875       4        0           1        1  0.408163  21.210        50   
10876       4        0           1        1  0.408163  21.210        50   
10877       4        0          

In [2]:
# 저장한 path 경로 정의
import os
path = (os.path.dirname(os.path.abspath('CategoricalEncoding_Label_Ordinal_Onehot.ipynb')))
PRE_DATA = os.path.join(path, 'tmp_files')
PRE_DATA

'C:\\Users\\Daumsoft\\Desktop\\tmp_files'

In [3]:
# scaled 완료 후 전처리된 데이터 생성 - table옵션으로 저장하고 읽는 경우
save_path = os.path.join(PRE_DATA,'save_as_table.json')
#bike_2.to_json(save_path, orient='table') #또는 columns

In [10]:
import json
with open(save_path) as json_file:
    print(type(json_file))
    json_data = json.load(json_file)
    print(type(json_data))
    
    
json_data

<class '_io.TextIOWrapper'>
<class 'dict'>


{'data': [{'atemp': 14.395,
   'casual': 3,
   'holiday': 0,
   'humidity': 81,
   'index': 0,
   'season': 1,
   'target': 16,
   'temp': 0.2244897959,
   'weather': 1,
   'windspeed': 0.0,
   'workingday': 0},
  {'atemp': 13.635,
   'casual': 8,
   'holiday': 0,
   'humidity': 80,
   'index': 1,
   'season': 1,
   'target': 40,
   'temp': 0.2040816327,
   'weather': 1,
   'windspeed': 0.0,
   'workingday': 0},
  {'atemp': 13.635,
   'casual': 5,
   'holiday': 0,
   'humidity': 80,
   'index': 2,
   'season': 1,
   'target': 32,
   'temp': 0.2040816327,
   'weather': 1,
   'windspeed': 0.0,
   'workingday': 0},
  {'atemp': 14.395,
   'casual': 3,
   'holiday': 0,
   'humidity': 75,
   'index': 3,
   'season': 1,
   'target': 13,
   'temp': 0.2244897959,
   'weather': 1,
   'windspeed': 0.0,
   'workingday': 0},
  {'atemp': 14.395,
   'casual': 0,
   'holiday': 0,
   'humidity': 75,
   'index': 4,
   'season': 1,
   'target': 1,
   'temp': 0.2244897959,
   'weather': 1,
   'windspeed':

In [8]:
with open(save_path, 'r') as json_file:
    print(type(json_file))
    json_data = json.loads(json_file.read())
    print(type(json_data))

json_data

<class '_io.TextIOWrapper'>
<class 'dict'>


{'data': [{'atemp': 14.395,
   'casual': 3,
   'holiday': 0,
   'humidity': 81,
   'index': 0,
   'season': 1,
   'target': 16,
   'temp': 0.2244897959,
   'weather': 1,
   'windspeed': 0.0,
   'workingday': 0},
  {'atemp': 13.635,
   'casual': 8,
   'holiday': 0,
   'humidity': 80,
   'index': 1,
   'season': 1,
   'target': 40,
   'temp': 0.2040816327,
   'weather': 1,
   'windspeed': 0.0,
   'workingday': 0},
  {'atemp': 13.635,
   'casual': 5,
   'holiday': 0,
   'humidity': 80,
   'index': 2,
   'season': 1,
   'target': 32,
   'temp': 0.2040816327,
   'weather': 1,
   'windspeed': 0.0,
   'workingday': 0},
  {'atemp': 14.395,
   'casual': 3,
   'holiday': 0,
   'humidity': 75,
   'index': 3,
   'season': 1,
   'target': 13,
   'temp': 0.2244897959,
   'weather': 1,
   'windspeed': 0.0,
   'workingday': 0},
  {'atemp': 14.395,
   'casual': 0,
   'holiday': 0,
   'humidity': 75,
   'index': 4,
   'season': 1,
   'target': 1,
   'temp': 0.2244897959,
   'weather': 1,
   'windspeed':

In [77]:
# https://stackoverflow.com/questions/43897628/is-there-a-way-i-can-read-the-json-file-saved-by-dataframe-to-jsonorient-table
def table_to_df(table):
    df = pd.DataFrame(table['data'],
                      columns=[t['name'] for t in table['schema']['fields']])
    for t in table['schema']['fields']:
        if t['type'] == "datetime":
            df[t['name']] = pd.to_datetime(df[t['name']], infer_datetime_format=True)
    #df.set_index(table['schema']['primaryKey'], inplace=True)
    df = df.drop('index', axis=1)
    return df

df = table_to_df(json_obj)
df

season  holiday  workingday  weather      temp   atemp  humidity  \
0           1        0           0        1  0.224490  14.395        81   
1           1        0           0        1  0.204082  13.635        80   
2           1        0           0        1  0.204082  13.635        80   
3           1        0           0        1  0.224490  14.395        75   
4           1        0           0        1  0.224490  14.395        75   
5           1        0           0        2  0.224490  12.880        75   
6           1        0           0        1  0.204082  13.635        80   
7           1        0           0        1  0.183673  12.880        86   
8           1        0           0        1  0.224490  14.395        75   
9           1        0           0        1  0.306122  17.425        76   
10          1        0           0        1  0.367347  19.695        76   
11          1        0           0        1  0.346939  16.665        81   
12          1        0           0        1  0.408163  21.210        77   
13          1        0           0        2  0.448980  22.725        72   
14          1        0           0        2  0.448980  22.725        72   
15          1        0           0        2  0.428571  21.970        77   
16          1        0           0        2  0.408163  21.210        82   
17          1        0           0        2  0.428571  21.970        82   
18          1        0           0        3  0.408163  21.210        88   
19          1        0           0        3  0.408163  21.210        88   
20          1        0           0        2  0.387755  20.455        87   
21          1        0           0        2  0.387755  20.455        87   
22          1        0           0        2  0.387755  20.455        94   
23          1        0           0        2  0.448980  22.725        88   
24          1        0           0        2  0.448980  22.725        88   
25          1        0           0        2  0.428571  21.970        94   
26          1        0           0        2  0.408163  21.210       100   
27          1        0           0        2  0.448980  22.725        94   
28          1        0           0        2  0.448980  22.725        94   
29          1        0           0        3  0.408163  21.210        77   
...       ...      ...         ...      ...       ...     ...       ...   
10856       4        0           1        1  0.367347  19.695        46   
10857       4        0           1        1  0.367347  19.695        46   
10858       4        0           1        1  0.346939  16.665        50   
10859       4        0           1        1  0.346939  17.425        50   
10860       4        0           1        1  0.326531  16.665        49   
10861       4        0           1        1  0.326531  17.425        49   
10862       4        0           1        1  0.285714  15.910        61   
10863       4        0           1        1  0.285714  15.910        65   
10864       4        0           1        1  0.265306  15.150        65   
10865       4        0           1        1  0.244898  13.635        75   
10866       4        0           1        1  0.224490  12.120        75   
10867       4        0           1        1  0.244898  14.395        75   
10868       4        0           1        1  0.224490  12.880        75   
10869       4        0           1        1  0.244898  13.635        75   
10870       4        0           1        1  0.224490  12.880        87   
10871       4        0           1        1  0.265306  14.395        75   
10872       4        0           1        1  0.306122  16.665        70   
10873       4        0           1        1  0.387755  20.455        54   
10874       4        0           1        1  0.387755  20.455        54   
10875       4        0           1        1  0.408163  21.210        50   
10876       4        0           1        1  0.408163  21.210        50   
10877       4        0          

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 10 columns):
season        10886 non-null int64
holiday       10886 non-null int64
workingday    10886 non-null int64
weather       10886 non-null int64
temp          10886 non-null float64
atemp         10886 non-null float64
humidity      10886 non-null int64
windspeed     10886 non-null float64
casual        10886 non-null int64
target        10886 non-null int64
dtypes: float64(3), int64(7)
memory usage: 850.5 KB


In [125]:
# scaled 완료 후 전처리된 데이터 생성 - index옵션으로 저장하고 읽는 경우
save_path = os.path.join(PRE_DATA,'P_13.json')
bike.to_json(save_path, orient='index') #또는 columns

In [126]:
save_path

'C:\\Users\\Daumsoft\\Desktop\\tmp_files\\P_13.json'

In [127]:
import json
with open(save_path) as json_file:
    json_data = json.load(json_file)

In [128]:
json_data['0']

{'atemp': 0.3050676809,
 'casual': 3,
 'holiday': 0,
 'humidity': 0.62,
 'season': 1,
 'target': 16,
 'temp': 0.2244897959,
 'weather': 1,
 'windspeed': 0.0,
 'workingday': 0}

In [129]:
js_to_df = pd.DataFrame.from_dict(json_data, orient='index') #또는 columns
js_to_df.index = js_to_df.index.astype(int)
js_to_df = js_to_df.sort_index()
js_to_df.head()

season  holiday  workingday  weather      temp     atemp  humidity  \
0       1        0           0        1  0.224490  0.305068      0.62   
1       1        0           0        1  0.204082  0.288064      0.60   
2       1        0           0        1  0.204082  0.288064      0.60   
3       1        0           0        1  0.224490  0.305068      0.50   
4       1        0           0        1  0.224490  0.305068      0.50   

   windspeed  casual  target  
0        0.0       3      16  
1        0.0       8      40  
2        0.0       5      32  
3        0.0       3      13  
4        0.0       0       1

In [16]:
js_to_df.drop()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10886 entries, 0 to 10885
Data columns (total 12 columns):
datetime      10886 non-null object
season        10886 non-null int64
holiday       10886 non-null int64
workingday    10886 non-null int64
weather       10886 non-null int64
temp          10886 non-null float64
atemp         10886 non-null float64
humidity      10886 non-null int64
windspeed     10886 non-null float64
casual        10886 non-null int64
registered    10886 non-null int64
target        10886 non-null int64
dtypes: float64(3), int64(8), object(1)
memory usage: 1.1+ MB


## **전처리된 데이터 db SUMMARY정보 파싱** ##

In [503]:
js_to_df = pd.DataFrame.from_dict(json_data, orient='index') #또는 columns
js_to_df.index = js_to_df.index.astype(int)
js_to_df.sort_index().head()

datetime  holiday  workingday  weather      temp     atemp  \
0  2011-01-01 00:00        0           0        1  0.224490  0.305068   
1  2011-01-01 01:00        0           0        1  0.204082  0.288064   
2  2011-01-01 02:00        0           0        1  0.204082  0.288064   
3  2011-01-01 03:00        0           0        1  0.224490  0.305068   
4  2011-01-01 04:00        0           0        1  0.224490  0.305068   

   humidity  windspeed  casual  registered  target  season_0  season_1  \
0      0.62        0.0       3          13      16       1.0       0.0   
1      0.60        0.0       8          32      40       1.0       0.0   
2      0.60        0.0       5          27      32       1.0       0.0   
3      0.50        0.0       3          10      13       1.0       0.0   
4      0.50        0.0       0           1       1       1.0       0.0   

   season_2  season_3  
0       0.0       0.0  
1       0.0       0.0  
2       0.0       0.0  
3       0.0       0.0  
4       0.0       0.0

In [467]:
some_summary = {
    "PREPROCESSED_DATA_SEQUENCE_PK": 78,
    "FILEPATH": "C:\\Users\\Daumsoft\\Miniconda3\\envs\\py36env\\daumsoft\\tmp_files/data_preprocessed\\P_78.json",
    "FILENAME": "P_78.json",
    "SUMMARY": "{'temp': {'encoder_name': 'MinMaxScaler', 'file_path': 'C:\\\\Users\\\\Daumsoft\\\\Miniconda3\\\\envs\\\\py36env\\\\daumsoft\\\\tmp_files/preprocess_transformer\\\\T_78_1.pickle', 'file_name': 'T_78_1.pickle'}, 'atemp': {'encoder_name': 'MinMaxScaler', 'file_path': 'C:\\\\Users\\\\Daumsoft\\\\Miniconda3\\\\envs\\\\py36env\\\\daumsoft\\\\tmp_files/preprocess_transformer\\\\T_78_2.pickle', 'file_name': 'T_78_2.pickle'}, 'humidity': {'encoder_name': 'MinMaxScaler', 'file_path': 'C:\\\\Users\\\\Daumsoft\\\\Miniconda3\\\\envs\\\\py36env\\\\daumsoft\\\\tmp_files/preprocess_transformer\\\\T_78_3.pickle', 'file_name': 'T_78_3.pickle'}, 'season': {'encoder_name': 'OneHotEncoder', 'orginal_classes': [1.0, 2.0, 3.0, 4.0], 'encoded_classes': ([[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]],), 'file_path': 'C:\\\\Users\\\\Daumsoft\\\\Miniconda3\\\\envs\\\\py36env\\\\daumsoft\\\\tmp_files/preprocess_transformer\\\\T_78_4.pickle', 'file_name': 'T_78_4.pickle'}, 'file_path': 'C:\\\\Users\\\\Daumsoft\\\\Miniconda3\\\\envs\\\\py36env\\\\daumsoft\\\\tmp_files/data_preprocessed\\\\P_78.json', 'file_name': 'P_78.json'}",
    "CREATE_DATETIME": "2019-09-05T15:52:40.342363+09:00",
    "PROGRESS_STATE": "success",
    "PROGRESS_START_DATETIME": "2019-09-05T15:52:40.521881+09:00",
    "PROGRESS_END_DATETIME": "2019-09-05T15:52:43.345326+09:00",
    "DELETE_FLAG": "false",
    "ORIGINAL_DATA_SEQUENCE_FK1": 21
}

In [476]:
some_summary['SUMMARY']
#json.loads(some_summary['SUMMARY'])

"{'temp': {'encoder_name': 'MinMaxScaler', 'file_path': 'C:\\\\Users\\\\Daumsoft\\\\Miniconda3\\\\envs\\\\py36env\\\\daumsoft\\\\tmp_files/preprocess_transformer\\\\T_78_1.pickle', 'file_name': 'T_78_1.pickle'}, 'atemp': {'encoder_name': 'MinMaxScaler', 'file_path': 'C:\\\\Users\\\\Daumsoft\\\\Miniconda3\\\\envs\\\\py36env\\\\daumsoft\\\\tmp_files/preprocess_transformer\\\\T_78_2.pickle', 'file_name': 'T_78_2.pickle'}, 'humidity': {'encoder_name': 'MinMaxScaler', 'file_path': 'C:\\\\Users\\\\Daumsoft\\\\Miniconda3\\\\envs\\\\py36env\\\\daumsoft\\\\tmp_files/preprocess_transformer\\\\T_78_3.pickle', 'file_name': 'T_78_3.pickle'}, 'season': {'encoder_name': 'OneHotEncoder', 'orginal_classes': [1.0, 2.0, 3.0, 4.0], 'encoded_classes': ([[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]],), 'file_path': 'C:\\\\Users\\\\Daumsoft\\\\Miniconda3\\\\envs\\\\py36env\\\\daumsoft\\\\tmp_files/preprocess_transformer\\\\T_78_4.pickle', 'file_name': 'T_78_4.pickle'

In [493]:
from ast import literal_eval
summary_dict = literal_eval(some_summary['SUMMARY'])
summary_dict.keys()

dict_keys(['temp', 'atemp', 'humidity', 'season', 'file_path', 'file_name'])

In [497]:
summary_dict.pop('file_path', None)
summary_dict.pop('file_name', None)
summary_dict.keys()

dict_keys(['temp', 'atemp', 'humidity', 'season'])

In [500]:
for k, v in summary_dict.items():
    print(k)
    print(v)
    

temp
{'encoder_name': 'MinMaxScaler', 'file_path': 'C:\\Users\\Daumsoft\\Miniconda3\\envs\\py36env\\daumsoft\\tmp_files/preprocess_transformer\\T_78_1.pickle', 'file_name': 'T_78_1.pickle'}
atemp
{'encoder_name': 'MinMaxScaler', 'file_path': 'C:\\Users\\Daumsoft\\Miniconda3\\envs\\py36env\\daumsoft\\tmp_files/preprocess_transformer\\T_78_2.pickle', 'file_name': 'T_78_2.pickle'}
humidity
{'encoder_name': 'MinMaxScaler', 'file_path': 'C:\\Users\\Daumsoft\\Miniconda3\\envs\\py36env\\daumsoft\\tmp_files/preprocess_transformer\\T_78_3.pickle', 'file_name': 'T_78_3.pickle'}
season
{'encoder_name': 'OneHotEncoder', 'orginal_classes': [1.0, 2.0, 3.0, 4.0], 'encoded_classes': ([[1.0, 0.0, 0.0, 0.0], [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0], [0.0, 0.0, 0.0, 1.0]],), 'file_path': 'C:\\Users\\Daumsoft\\Miniconda3\\envs\\py36env\\daumsoft\\tmp_files/preprocess_transformer\\T_78_4.pickle', 'file_name': 'T_78_4.pickle'}


## **ptyon dict - keep key add new values**

In [40]:
prepro={}
prepro['atemp'] = 'minmax'
prepro

{'atemp': 'minmax'}

In [41]:
preprocessed_data_info={}
preprocessed_data_info.setdefault('atemp', [])
preprocessed_data_info['atemp'].append('minmax')
preprocessed_data_info.setdefault('atemp', [])
preprocessed_data_info.setdefault('temp', [])
preprocessed_data_info['temp'].append('drop')
preprocessed_data_info['atemp'].append(prepro)
preprocessed_data_info

{'atemp': ['minmax', {'atemp': 'minmax'}], 'temp': ['drop']}

In [45]:
#여러개의 모델을 session에 로드하기
request_session = {} #원래는 request.session
model_id = 1
request_session[model_id] = "something bytes type"
request_session

{1: 'something bytes type'}

In [46]:
model_id = 2
request_session[model_id] = "something different bytes type"
request_session

{1: 'something bytes type', 2: 'something different bytes type'}

In [47]:
request_session[1]

'something bytes type'

In [1]:
dict_string = "{'model_name': 'RandomForestRegressor', 'model_param': {'bootstrap': True, 'criterion': 'mse', 'max_depth': None, 'max_features': 'auto', 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 10, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}, 'model_train_columns': ['season', 'holiday', 'workingday', 'weather', 'temp', 'atemp', 'humidity', 'windspeed', 'casual']}"

In [2]:
dict_string

"{'model_name': 'RandomForestRegressor', 'model_param': {'bootstrap': True, 'criterion': 'mse', 'max_depth': None, 'max_features': 'auto', 'max_leaf_nodes': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 10, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}, 'model_train_columns': ['season', 'holiday', 'workingday', 'weather', 'temp', 'atemp', 'humidity', 'windspeed', 'casual']}"

In [3]:
def inspect_condition(params_str): 
    params_dict = {}
    condition_list = params_str.split(', ')
    if len(condition_list) != 1: #요청한 파라미터 변경 개수가 2개 이상인 경우 
        for request_conidtion in condition_list:
            key_, values_ = request_conidtion.split(':')[0], request_conidtion.split(':')[1]
            params_dict[key_] = values_
    else: #요청한 파라미터 변경 개수가 하나인 경우 
        params_dict[condition_list[0].split(':')[0]] = condition_list[0].split(':')[1]
    return params_dict

In [9]:
from ast import literal_eval 
str_to_dict = literal_eval(dict_string)
print(type(str_to_dict), str_to_dict.keys())
str_to_dict

<class 'dict'> dict_keys(['model_name', 'model_param', 'model_train_columns'])


{'model_name': 'RandomForestRegressor',
 'model_param': {'bootstrap': True,
  'criterion': 'mse',
  'max_depth': None,
  'max_features': 'auto',
  'max_leaf_nodes': None,
  'min_impurity_decrease': 0.0,
  'min_impurity_split': None,
  'min_samples_leaf': 1,
  'min_samples_split': 2,
  'min_weight_fraction_leaf': 0.0,
  'n_estimators': 10,
  'n_jobs': None,
  'oob_score': False,
  'random_state': None,
  'verbose': 0,
  'warm_start': False},
 'model_train_columns': ['season',
  'holiday',
  'workingday',
  'weather',
  'temp',
  'atemp',
  'humidity',
  'windspeed',
  'casual']}

In [11]:
len(str_to_dict['model_train_columns'])

9